name: solargraph
base: core18
version: 0.45.0
summary: A Ruby Language Server
description: |
  Solargraph provides a comprehensive suite of tools for Ruby programming:
  intellisense, diagnostics, inline documentation, and type checking.

grade: stable
confinement: strict

apps:
  solargraph:
    command: bin/solargraph
    plugs:
      - home
      - removable-media

parts:
  solargraph:
    plugin: ruby
    source: .
    ruby-version: 2.6.10
    gems:
      - solargraph

